/*
 * This file is generated by jOOQ.
 */
package de.haumacher.wizard.server.db.h2.schema;


import de.haumacher.wizard.server.db.h2.schema.tables.EmailToken;
import de.haumacher.wizard.server.db.h2.schema.tables.UserSession;
import de.haumacher.wizard.server.db.h2.schema.tables.Users;
import de.haumacher.wizard.server.db.h2.schema.tables.records.EmailTokenRecord;
import de.haumacher.wizard.server.db.h2.schema.tables.records.UserSessionRecord;
import de.haumacher.wizard.server.db.h2.schema.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EmailTokenRecord> EMAIL_TOKEN_PK = Internal.createUniqueKey(EmailToken.EMAIL_TOKEN, DSL.name("EMAIL_TOKEN_PK"), new TableField[] { EmailToken.EMAIL_TOKEN.UID }, true);
    public static final UniqueKey<UserSessionRecord> USER_SESSION_PK = Internal.createUniqueKey(UserSession.USER_SESSION, DSL.name("USER_SESSION_PK"), new TableField[] { UserSession.USER_SESSION.UID }, true);
    public static final UniqueKey<UsersRecord> USERS_PK = Internal.createUniqueKey(Users.USERS, DSL.name("USERS_PK"), new TableField[] { Users.USERS.UID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UserSessionRecord, UsersRecord> USER_SESSION_FK = Internal.createForeignKey(UserSession.USER_SESSION, DSL.name("USER_SESSION_FK"), new TableField[] { UserSession.USER_SESSION.UID }, Keys.USERS_PK, new TableField[] { Users.USERS.UID }, true);
}
