/*
 * This file is generated by jOOQ.
 */
package de.haumacher.wizard.server.db.h2.schema;


import de.haumacher.wizard.server.db.h2.schema.tables.EmailToken;
import de.haumacher.wizard.server.db.h2.schema.tables.UserSession;
import de.haumacher.wizard.server.db.h2.schema.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.EMAIL_TOKEN</code>.
     */
    public final EmailToken EMAIL_TOKEN = EmailToken.EMAIL_TOKEN;

    /**
     * The table <code>PUBLIC.USER_SESSION</code>.
     */
    public final UserSession USER_SESSION = UserSession.USER_SESSION;

    /**
     * The table <code>PUBLIC.USERS</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            EmailToken.EMAIL_TOKEN,
            UserSession.USER_SESSION,
            Users.USERS
        );
    }
}
