/*
 * This file is generated by jOOQ.
 */
package de.haumacher.wizard.server.db.h2.schema;


import de.haumacher.wizard.server.db.h2.schema.tables.EmailToken;
import de.haumacher.wizard.server.db.h2.schema.tables.UserSession;
import de.haumacher.wizard.server.db.h2.schema.tables.Users;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.EMAIL_TOKEN</code>.
     */
    public static final EmailToken EMAIL_TOKEN = EmailToken.EMAIL_TOKEN;

    /**
     * The table <code>PUBLIC.USER_SESSION</code>.
     */
    public static final UserSession USER_SESSION = UserSession.USER_SESSION;

    /**
     * The table <code>PUBLIC.USERS</code>.
     */
    public static final Users USERS = Users.USERS;
}
