-- PUBLIC.USERS definition

-- Drop table

-- DROP TABLE PUBLIC.USERS;

CREATE TABLE PUBLIC.USERS (
	UID CHARACTER VARYING(64) NOT NULL,
	NICKNAME CHARACTER VARYING(64) NOT NULL,
	EMAIL CHARACTER VARYING(256),
	"LANGUAGE" CHARACTER VARYING(5) NOT NULL,
	CREATED BIGINT NOT NULL,
	VERIFIED BOOLEAN NOT NULL,
	LAST_LOGIN BIGINT NOT NULL,
	CONSTRAINT USERS_PK PRIMARY KEY (UID)
);
CREATE UNIQUE INDEX USERS_EMAIL_INDEX_6 ON PUBLIC.USERS (EMAIL);
CREATE UNIQUE INDEX USERS_UN_INDEX_6 ON PUBLIC.USERS (NICKNAME);

-- PUBLIC.USER_SESSION definition

-- Drop table

-- DROP TABLE PUBLIC.USER_SESSION;

CREATE TABLE PUBLIC.USER_SESSION (
	UID CHARACTER VARYING(64) NOT NULL,
	HASH BINARY VARYING(128) NOT NULL,
	CONSTRAINT USER_SESSION_PK PRIMARY KEY (UID)
);


-- PUBLIC.USER_SESSION foreign keys

ALTER TABLE PUBLIC.USER_SESSION ADD CONSTRAINT USER_SESSION_FK FOREIGN KEY (UID) REFERENCES PUBLIC.USERS(UID) ON DELETE CASCADE ON UPDATE RESTRICT;

-- PUBLIC.EMAIL_TOKEN definition

-- Drop table

-- DROP TABLE PUBLIC.EMAIL_TOKEN;

CREATE TABLE PUBLIC.EMAIL_TOKEN (
	EMAIL CHARACTER VARYING(256) NOT NULL,
	HASH BINARY VARYING(128) NOT NULL,
	NOT_AFTER BIGINT NOT NULL,
	CONSTRAINT EMAIL_TOKEN_PK PRIMARY KEY (EMAIL)
);


